name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.1'

      # Remove node_modules
      - name: Remove node_modules
        run: |
          rm -rf node_modules

      # Install dependencies and build the front-end
      - name: Install dependencies and build front-end
        run: |
          npm install
          npm run build

      # Deploy front-end to Render
      - name: Deploy front-end to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/deploy/srv-xxxxxxxxxxx" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY"

      # Remove node_modules for backend
      - name: Remove node_modules (backend)
        working-directory: ./server
        run: |
          rm -rf node_modules

      # Install dependencies and start back-end
      - name: Install dependencies and start back-end
        working-directory: ./server
        run: |
          npm install
          npm start

      # Deploy back-end to Render
      - name: Deploy back-end to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/deploy/srv-yyyyyyyyyyy" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY"
